### PR TITLE
Added missing require statement.

### PR DESCRIPTION
**Pull request by zw963**

### CODE REVIEW

**Comment by zw963** [comment]
One more question, why we add [those two line](https://github.com/ralsina/oplog/blob/main/src/oplog.cr#L38-L39)? 

Thanks

**Comment by ralsina** [comment]
> One more question, why we add [those two line](https://github.com/ralsina/oplog/blob/main/src/oplog.cr#L38-L39)?
> 
> Thanks

Ensures the verbosity is in the acceptable range.

**Comment by ralsina** [comment]
Thanks for the fix!

**Comment by zw963** [comment]
> > One more question, why we add [those two line](https://github.com/ralsina/oplog/blob/main/src/oplog.cr#L38-L39)?
> > Thanks
> 
> Ensures the verbosity is in the acceptable range.

Why not passing `Log::Severity` enum type directly? we can still convert numbers to enum use `Log::Severity.from_value(1)`, it will raise if not valid.

**Comment by ralsina** [comment]
Because I don't want it to raise, if the user sets it to 99, I just want it
to be the maximum

**Pull request merged**
